### ISSUE TITLE
Initial data model

### ISSUE THREAD

**Issue by acuarica** [epam/mintgate#2]
Draft for the data model on the NFT contract.

```rust
type TokenId = serial u128;
type GateId = String;

struct Contract {
  collectibles_by_creator: Map<AccountId, GateId>,
  collectibles: Map<GateId, Collectible>,
  tokens: Map<TokenId, Token>,
  tokens_by_owner: Map<AccountId, TokenId>,
  metadata: NFT::NFTMetadata,
  fee: u128, // Set up when contract is deployed
}

struct Collectible { 
  gate_id: GateId,
  creator_id: AccountId,
  current_supply: u64,
  royalty: NFT::Fraction // (%), List of beneficiaries<creator>, List of <(beneficiaries, fraction)>
  minted_tokens: List<TokenId>,
  metadata: NFT::TokenMetadata,
}

struct Token {
  token_id: TokenId,
  owner_id: AccountId,
  gate_id: String|Index into gates
}
```

**Comment by zahhar** [comment]
@acuarica - shall we add common attributes, like owner_id for Token and creator_id for Collectible?

**Comment by acuarica** [comment]
Yes, sounds good. I'll edit the description.

**Comment by zahhar** [comment]
@acuarica - just realized that "Fee" does not belong here. It is attribute of Marketplace contract.

**Comment by zahhar** [comment]
@Jshanks21 - we have one open question regarding Data Model. 

According to recently published NEAR NFT Standard there will be "_hash" attributes to store sha256 hash of the off-chain content, e.g. extrenal metadata or media file itself. Our contract will NOT verify correctness of any, but will panic if hash is not given. This requires caller party to calculate sha256 hash of the resource and pass it as additional argument. Hope this is fine — technically it is very simple. Ofc, verification of hash is up to the consumer.

**Comment by zahhar** [comment]
Folks, let's discuss if we need to make any attributes on Metadata (like Media probably?) mandatory in the data model that has to be validated by the contract itself?

**Comment by zahhar** [comment]
@acuarica  - few observations:

1. `pub struct ContractMetadata { .. }` → shall we rename to `NFTContractMetadata` to match the standard?


2. Shall we remove `gate_url` from `Collectible`? I do not see any use-case. Full URL can be constructed by concatenating  NFTContractMetadata.base_uri and gate_id value, and it is task for consumer. We assume that all Collectibles share same base_uri as they are stored in one contract.
```
pub struct Collectible {
    pub gate_url: String, 
}
```
3. Most complicated issue is with Token struct. 
- 3a: do we need `sender_id` to be stored? I do not see a use-case for it in this project. If absolutely needed, Indexer has this in transaction history.
- 3b: we DO NOT need to copy gate_id into Metadata, because gate_id exists on the Token struct and will be returned. No need to duplicate I think.
- 3c: we have `created_at` & `modified_at` attributes. `TokenMetadata` struct that will be injected into Token struct also has attributes of the same meaning, but named differently. However, in our case `TokenMetadata` struct represents `Collectible`, so `issued_at` and `updated_at` will hold timestamps when Collectible was created (that makes sense, because we want to certify when Creator instantiated his/hers Collectible on-chain. But it will be confusing when TokenMetadata gets attached to the Token struct. One option I am thinking about is to overwrite data in TokenMetadata struct: `created_at`→`issued_at`, `modified_at` → `updated_at`, and not expose `created_at` & `modified_at` when Token struct is returned not to get anyone confused. Or keep them as-is and just document this peculiarity. Just thinking what happens to our Token if it gets to 3rd party marketplace one day (not owned by Mintgate) and thus relying on standard? Such marketplace would assume that Metadata fully belongs to Token itself. 

```
pub struct Token {
    /// The unique identifier for a `Token`.
    /// Any two different tokens, will have different `token_id`s,
    /// even if they belong to different `gate_id`s.
    pub token_id: TokenId,
    pub gate_id: GateId,
    /// The owner of this token.
    pub owner_id: AccountId,
    /// Represents when this `Token` was minted, in nanoseconds.
    /// Once this `Token` is minted, this field remains unchanged.
    pub created_at: u64,
    /// Represents when this `Token` was last modified, in nanoseconds.
    /// Either when created or transferred.
    pub modified_at: u64,
    /// If this `Token` was transferred, this field holds the previous owner.
    /// Otherwise is empty.
    pub sender_id: AccountId,
    /// Holds the list of accounts that can `transfer_token`s on behalf of the token's owner.
    /// It is mapped to the approval id and minimum amount that this token should be transfer for.
    pub approvals: HashMap<AccountId, TokenApproval>,
    /// Counter to assign next approval ID.
    pub approval_counter: U64,
}
```
