### ISSUE TITLE
F1: As a Creator, I want to make my Collectable available for claiming as an NFT

### ISSUE THREAD

**Issue by zahhar** [epam/mintgate#3]
Tasks:

- [x] Agree on Data model - see #2 
- [x] Agree on Metadata
- [x] Agree on Royalty and who will get it

**Royalty**
> Q: is Royalty distributed to Artist who creates GateID only, or an arbitrary list of NEAR AccountIDs can be provided to split royalties between?
> 
> A: The royalty is distributed only to the Artist who creates the GateID. The Artist can choose a royalty between 5%-30%. Royalti is set only once and cannot be changed during NFT lifetime.
> 

- [x] Agree when Collectable is created as an NFT

**Comment by zahhar** [comment]
@acuarica - am I right that GateID should be registered in the contract (structure created) BEFORE first user will be able to claim it? E.g. Mintgate should have somewhere a button in the UI that calls _createCollectable_ contract method to set GateID, Supply, Royalty, ArtistAccountID and some metadata?

@Jshanks21 - is it OK for you? You have freedom to decide in your off-chain flow in what point in time this shall happen, but this must happen one before first copy will be claimed.

**Comment by Jshanks21** [comment]
This sounds like it would be fine. 

To make sure I understand, could we set GateID, Supply, Royalty, ArtistAccountID and metadata at the same time the user clicks "Claim"? So when a user clicks "Claim" we set this data and immediately mint the NFT to them.

Or would we need a separate flow to set this data first and then have the user claim it after?

On a separate note, the answer above about royalties is accurate, however, all NFTs created should _also_ have a fixed royalty of 2.5% that goes to a NEAR account MintGate controls. So 2.5% royalty on all NFTs that go to MintGate and between 5%-30% that goes only to the Artist who created said NFT.

I know this was mentioned previously, but I just wanted to be sure since it doesn't seem to be in the answer above.

**Comment by zahhar** [comment]
@Jshanks21 - there will be separate flow to instantiate GateID, Supply, Royalty, ArtistAccountID and metadata on the blockchain. However, none of the tokens will be minted when GateID gets instantiated on-chain. This instantiation step step must be done BEFORE the first user can claim the first Token for given GateID. 

Instantiation can be done either by ArtistAccountID OR by AdminAccointID. What would you prefer? Our current assumption is that ArtistAccountID does it, because Artist must have NEAR AccountID already available, and s_he must be logged into Mintgate with his/her wallet to become a Royalty receiver. ArtistAccountID also pays for the gas consumed during this operation. 

As of now we do not see any benefits why AdminAccointID should do instantiation — if you have any good arguments, please bring them.

**Comment by zahhar** [comment]
@acuarica - add check for Royalty amount within 5...30%
@sxurik - add relevant test for it

**Comment by zahhar** [comment]
@sxurik - closing, tested & demonstrated to client
