### ISSUE TITLE
[HIGH] F13: As an Owner, I want to give approval to all of my tokens to the Marketplace

### ISSUE THREAD

**Issue by zahhar** [epam/mintgate#62]
It would be preferable if the Owner is able to approve a batch sell orders to avoid approving individual items one at a time if they want to sell multiple. 

For example, if the Owner wants to approve to sell 3 tokens of a specific GateId, or even series of different TokenIds they hold, that would be ideal. Perhaps for the GateId approach, just selecting the GateId and then an amount, and for the TokenId approach we could allow them to select from the TokenIds they currently own and each could be approved.

**Comment by zahhar** [comment]
```
pub fn nft_batch_approve(
    &mut self,
    token_ids: Vec<U64>,
    account_id: AccountId,
    msg: Option<String>,
  ) -> Option<Promise> {
```
with a mirrored method on our market
```
#[ext_contract(ext_on_approve)]
pub trait NonFungibleOnBatchApprove {
  /// The Mintiest-base special, `nft_batch_on_approve` allows for batch
  /// approval of a set of tokens.
  fn nft_on_batch_approve(
    &mut self,
    tokens: Vec<U64>,
    approvals: Vec<U64>,
    owner_id: AccountId,
    msg: String,
  );
}
```

**Comment by zahhar** [comment]
As an Owner, I want to approve batch of N out of M tokens within one Colleection in my posession.

**Comment by acuarica** [comment]
I see some issues in the implementation of batch approvals:

- [ ] Since this methods are not part of the standard, can we drop the `nft_` prefix? *e.g.*, `batch_approve` instead of `nft_batch_approve`
- [ ] How can we pass the `min_price` for each token? Maybe instead of `token_ids: Vec<U64>`, we could use `token_ids: Vec<(U64, Balance)>` and remove `msg` parameter.
- [ ] How should we handle panics? In case of some tokens not belonging to the caller of `batch_approve`, should the method panic?
